#include "pch.h"

#include "WorldGenerationUtils.h"

// Generated by an external program.
// The idea is that if you keep using the result of the rand table as an index into the rand table you go through all numbers.
// And they're also random to begin with if you iterate, the possibilities are endless
static constexpr u8 RAND_BYTE_TABLE[256] = {41, 23, 185, 90, 115, 21, 183, 130, 165, 56, 50, 96, 62, 28, 95, 27, 76, 136, 77, 137, 242, 7, 230, 86, 112, 46, 162, 243, 6, 240, 156, 3, 154, 147, 145, 190, 94, 93, 223, 138, 11, 35, 229, 129, 128, 142, 188, 104, 161, 66, 32, 116, 63, 207, 253, 189, 37, 51, 16, 19, 135, 151, 153, 227, 120, 15, 124, 139, 102, 59, 106, 222, 117, 241, 119, 88, 236, 200, 113, 20, 238, 25, 144, 191, 206, 78, 198, 97, 210, 53, 125, 184, 195, 212, 13, 141, 61, 255, 224, 38, 84, 122, 208, 45, 118, 143, 4, 196, 214, 98, 92, 1, 146, 226, 44, 47, 244, 217, 250, 215, 54, 254, 99, 5, 228, 9, 197, 170, 126, 14, 24, 239, 225, 248, 181, 12, 121, 10, 194, 31, 169, 123, 131, 205, 73, 157, 100, 175, 75, 155, 245, 39, 199, 36, 80, 168, 22, 218, 220, 164, 127, 34, 237, 152, 89, 193, 219, 134, 167, 149, 91, 0, 26, 79, 82, 111, 202, 133, 234, 166, 101, 231, 81, 71, 58, 114, 171, 233, 148, 110, 132, 103, 247, 140, 8, 163, 48, 213, 249, 182, 67, 204, 2, 252, 83, 209, 177, 211, 107, 30, 172, 72, 203, 178, 174, 232, 40, 42, 176, 60, 173, 186, 18, 109, 52, 108, 180, 65, 33, 192, 29, 85, 57, 235, 201, 179, 49, 251, 64, 87, 74, 187, 68, 160, 159, 69, 158, 43, 70, 55, 17, 221, 150, 246, 216, 105};

void WorldGenerationUtils::MutateSeed(RandSeed& r)
{
	r.byte[0] = RAND_BYTE_TABLE[r.byte[0]] ^ r.byte[7];
	r.byte[1] = RAND_BYTE_TABLE[r.byte[1]] ^ r.byte[0];
	r.byte[2] = RAND_BYTE_TABLE[r.byte[2]] ^ r.byte[1];
	r.byte[3] = RAND_BYTE_TABLE[r.byte[3]] ^ r.byte[2];
	r.byte[4] = RAND_BYTE_TABLE[r.byte[4]] ^ r.byte[3];
	r.byte[5] = RAND_BYTE_TABLE[r.byte[5]] ^ r.byte[4];
	r.byte[6] = RAND_BYTE_TABLE[r.byte[6]] ^ r.byte[5];
	r.byte[7] = RAND_BYTE_TABLE[r.byte[7]] ^ r.byte[6];
}

void MutateSeedByByte(RandSeed& r, u8 byte)
{
	u8 bytes[8] = {byte, byte, byte, byte, byte, byte, byte, byte};
	r.seed ^= *(reinterpret_cast<u64*>(&bytes));
	WorldGenerationUtils::MutateSeed(r);
}

float WorldGenerationUtils::RandFloat(RandSeed randSeed)
{
	MutateSeed(randSeed);

	const u16 randShort = 
	(((u16)(randSeed.byte[0] & 0b11)) << (u16)	6	) +
	(((u16)(randSeed.byte[1] & 0b11)) << (u16)	14	) +
	(((u16)(randSeed.byte[2] & 0b11)) << (u16)	12	) +
	(((u16)(randSeed.byte[3] & 0b11)) << (u16)	2	) +
	(((u16)(randSeed.byte[4] & 0b11)) << (u16)	0	) +
	(((u16)(randSeed.byte[5] & 0b11)) << (u16)	4	) +
	(((u16)(randSeed.byte[6] & 0b11)) << (u16)	8	) +
	(((u16)(randSeed.byte[7] & 0b11)) << (u16)	10	);

	return (float)randShort / (float)std::numeric_limits<u16>::max();
}

float WorldGenerationUtils::BasicNoise1D(float x, RandSeed seed, BasicNoiseParams params)
{
	// #TEMP: This once returned an insane number, see NosieBug.png on desktop
	
	const float gridSpace = x / (float)params.gridSize;
	const float lowerGridCoordinate = floor(gridSpace) * params.gridSize;
	const float upperGridCoordinate = ceil(gridSpace) * params.gridSize;

	// Get deterministic seeds for each grid point
	RandSeed lowerGridSeed = seed;
	RandSeed upperGridSeed = seed;
	MutateSeedByByte(lowerGridSeed, (u8)lowerGridCoordinate);
	MutateSeedByByte(upperGridSeed, (u8)upperGridCoordinate);

	// Get random gradents (-0.5f, 0.5f)
	const float lowerGridGradient = RandFloat(lowerGridSeed) - 0.5f;
	const float upperGridGradient = RandFloat(upperGridSeed) - 0.5f;

	const float distanceAlphaFromLowerGridPoint = (x - lowerGridCoordinate) / params.gridSize;
	const float distanceAlphaFromUpperGridPoint = (upperGridCoordinate - x) / params.gridSize;

	const float lowerGridTargetHeight = (lowerGridGradient * distanceAlphaFromLowerGridPoint * 2.0f);
	const float upperGridTargetHeight = (-upperGridGradient * distanceAlphaFromUpperGridPoint * 2.0f);

	const float finalheight = lowerGridTargetHeight * distanceAlphaFromUpperGridPoint * distanceAlphaFromUpperGridPoint + upperGridTargetHeight * distanceAlphaFromLowerGridPoint * distanceAlphaFromLowerGridPoint;
	
	return finalheight * params.magnitude * 4.8f; // Magic number to make it between -1.0f and 1.0f
}

void WorldGenerationUtils::Test(RandSeed randSeed)
{
	// *** Print random seed in binary ***
	{
		std::string debugString = "0b";
		for (int i = 63; i >= 0; --i)
		{
			debugString += ((randSeed.seed & ((u64)1 << i)) > 0) ? '1' : '0';
		}
		DOMLOG_INFO(debugString);
	}

	// *** FIND DUPLICATES IN MUTATE() ***
	//{
	//	std::set<u64> seeds;
	//	for (int i = 0; i < 10000000; ++i)
	//	{
	//		if (seeds.find(randSeed.seed) != seeds.end()) {DOMLOG_INFO("Duplicate:", i, randSeed.seed)}
	//		
	//		seeds.emplace(randSeed.seed);
	//		
	//		MutateSeed(randSeed);
	//	}
	//}

	// *** SEE IF FLOATS ARE LINEARLY DISTRIBUTED (paste into desmos) ***
	//{
	//	std::string debugString;
	//	std::ostringstream ss;
	//
	//	for (int i = 0; i < 1500; ++i)
	//	{
	//		ss << "(" << (float)i/500.f << "," << RandFloat(randSeed) << "),";
	//		MutateSeed(randSeed);
	//	}
	//
	//	debugString = ss.str();
	//}
	
	// *** 1D NOISE TEST (paste into desmos) ***
	//{
	//	std::string debugString;
	//	std::ostringstream ss;
	//
	//	SoftNoiseParams params = {};
	//	params.magnitude = 5.0f;
	//	params.gridSize = 2.0f;
	//
	//	BasicNoise1D(2.5f, randSeed, params);
	//
	//	for (int i = 0; i < 1500; ++i)
	//	{
	//		ss << "(" << (float)i/20.f << "," << BasicNoise1D((float)i/20.f, randSeed, params) << "),";
	//	}
	//
	//	debugString = ss.str();
	//}

	// *** COMBINE 1D NOISE TEST ***
	//{
	//	std::string debugString;
	//	std::ostringstream ss;
	//
	//	SoftNoiseParams paramsSmall = {};
	//	paramsSmall.magnitude = 5.0f;
	//	paramsSmall.gridSize = 1.0f;
	//
	//	SoftNoiseParams paramsMedium = {};
	//	paramsMedium.magnitude = 10.0f;
	//	paramsMedium.gridSize = 2.0f;
	//
	//	SoftNoiseParams paramsLarge = {};
	//	paramsLarge.magnitude = 20.0f;
	//	paramsLarge.gridSize = 4.0f;
	//
	//	RandSeed randSeedSmall = randSeed;
	//
	//	RandSeed randSeedMedium = randSeed;
	//	MutateSeed(randSeedMedium);
	//	
	//	RandSeed randSeedLarge = randSeed;
	//	MutateSeed(randSeedLarge);
	//	MutateSeed(randSeedLarge);
	//
	//	for (int i = 0; i < 1500; ++i)
	//	{
	//		const float coordinate = (float)i/20.f;
	//		ss << "(" << coordinate << "," << BasicNoise1D(coordinate, randSeedSmall, paramsSmall) + BasicNoise1D(coordinate, randSeedMedium, paramsMedium) + BasicNoise1D(coordinate, randSeedLarge, paramsLarge) << "),";
	//	}
	//
	//	debugString = ss.str();
	//}
}
